# Generated by Django 6.0.3 on 2026-04-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid1", models.CharField(max_length=255)),
                ("uid2", models.CharField(max_length=255)),
                ("uid3", models.CharField(max_length=255)),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("ge", "GE"),
                            ("philips", "Philips"),
                            ("siemens", "Siemens"),
                            ("mindray", "Mindray"),
                            ("drager", "Drager"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("birth_date", models.DateField()),
            ],
        ),
    ]
